# Generated by Django 5.2.7 on 2025-12-10 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code interne, ex: STUDENT_CANDIDATURE_ACCEPTED', max_length=100, unique=True)),
                ('title_template', models.CharField(help_text="Titre avec variables, ex: 'Candidature pour {stage}'", max_length=200)),
                ('body_template', models.TextField(help_text="Message avec variables, ex: 'Votre candidature pour {stage} a été acceptée.'")),
                ('target_role', models.CharField(choices=[('student', 'Étudiant'), ('doctor', 'Médecin'), ('chef', 'Chef de service'), ('responsable', 'Responsable d’hôpital'), ('admin', 'Administrateur'), ('all', 'Tous')], default='all', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=20)),
                ('category', models.CharField(choices=[('auth', 'Authentification'), ('offre', 'Offre de stage'), ('candidature', 'Candidature'), ('stage', 'Stage'), ('evaluation', 'Évaluation'), ('message', 'Message'), ('system', 'Système')], default='system', max_length=20)),
                ('url', models.CharField(blank=True, help_text='Lien vers la page concernée (optionnel)', max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comm_notif.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
