# Generated by Django 5.2.7 on 2025-12-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='speciality',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Service'),
        ),
    ]
